CREATE TABLE if NOT EXISTS current_rates (CURRENCY VARCHAR2(3) NOT NULL, RATE_DATE DATE, RATE NUMBER(8,4));
DELETE current_rates;
insert into current_rates(CURRENCY, RATE_DATE, RATE) VALUES ('EUR', '2017-09-16', 4.6612);
commit;